/** Render the `chardb-client` module for an app's handles. */

import type { Column } from "drizzle-orm";
import { type ApiHandle, type ApiRow, type JsonSchema, pascal as pascalWord, unique, words } from "./api-handles.ts";

export const RUST_HEADER = `//! Typed CharDB handles generated by \`chardb generate\`. Do not edit.
#![allow(dead_code, nonstandard_style, clippy::all, clippy::pedantic)]
`;
const MAX_WIDTH = 100;
const VALUE = "::serde_json::Value";
const KEYWORDS = new Set(
    "abstract as async await become box break const continue do dyn else enum extern false final fn for gen if impl in let loop macro match mod move mut override priv pub ref return static struct trait true try type typeof unsafe unsized use virtual where while yield".split(
        " "
    )
);
const UNRAWABLE = new Set(["self", "Self", "super", "crate"]);
/** Rust type per Drizzle `dataType` once the driver has mapped the SQLite value to JSON. */
const COLUMN_TYPES: Readonly<Record<string, string>> = { string: "String", number: "f64", boolean: "bool" };
/** JSON Schema scalars with one fixed Rust spelling. */
const SCALARS: Readonly<Record<string, string>> = { integer: "i64", number: "f64", boolean: "bool" };

function columnType(column: Column): string {
    const base = column.columnType === "SQLiteInteger" ? "i64" : (COLUMN_TYPES[column.dataType] ?? VALUE);
    return column.notNull ? base : `Option<${base}>`;
}

/** A Rust string literal: JSON escapes such as `\f` and `\uXXXX` are not Rust, and Rust has no lone surrogates. */
function rustString(text: string): string {
    const escaped = text.replaceAll(/["\\\p{Cc}\p{Cs}]/gu, character =>
        character === '"' || character === "\\"
            ? `\\${character}`
            : `\\u{${(/\p{Cs}/u.test(character) ? 0xfffd : (character.codePointAt(0) ?? 0)).toString(16)}}`
    );
    return `"${escaped}"`;
}

/** Text placed in a `///` comment, so it must stay on its line. */
function docText(text: string): string {
    return text.replaceAll(/[\p{Cc}\p{Cs}]/gu, "");
}

function pascal(text: string): string {
    const name = pascalWord(text);
    return UNRAWABLE.has(name) ? `${name}_` : name;
}

function snake(text: string): string {
    const name = words(text).join("_");
    return /^\p{N}/u.test(name) ? `_${name}` : name || "unnamed";
}

function fieldIdent(key: string): string {
    const name = snake(key);
    return KEYWORDS.has(name) ? `r#${name}` : UNRAWABLE.has(name) ? `${name}_` : name;
}

function field(key: string, ident: string, kind: string, optional: boolean): string {
    return `${optional ? '    #[serde(skip_serializing_if = "Option::is_none")]\n' : ""}${
        ident.replace(/^r#/, "") === key ? "" : `    #[serde(rename = ${rustString(key)})]\n`
    }    pub ${ident}: ${kind},\n`;
}

class Generator {
    items = "";
    queries = "";
    mutations = "";
    private readonly types = new Set<string>();
    private readonly consts = new Set<string>();
    private readonly rows = new Map<string, string>();

    handle(kind: "Query" | "Mutation", name: string, reference: string, args: string, output: string): void {
        const head = `pub const ${unique(this.consts, snake(name).toUpperCase())}: ${kind}<${args}, ${output}> =`;
        const tail = `${kind}::new(${rustString(reference)});`;
        const gap = head.length + tail.length < MAX_WIDTH ? " " : "\n    ";
        this[kind === "Query" ? "queries" : "mutations"] += `/// \`${docText(reference)}\`\n${head}${gap}${tail}\n\n`;
    }

    argsType(owner: string, schema: JsonSchema | null): string {
        if (!schema) return VALUE;
        if (schema.type === "object" && schema.properties) {
            return this.objectStruct(`${pascal(owner)}Args`, schema, `Arguments for \`${docText(owner)}\`.`);
        }
        return this.typeOf(pascal(owner), "Args", schema);
    }

    rowType(row: ApiRow): string {
        const known = this.rows.get(row.table);
        if (known) return known;
        const name = unique(this.types, `${pascal(row.table)}Row`);
        this.rows.set(row.table, name);
        const fields = new Set<string>();
        const body = row.columns
            .map(({ key, column }) => field(key, unique(fields, fieldIdent(key)), columnType(column), false))
            .join("");
        this.items += `/// One \`${row.table}\` row.\n#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\npub struct ${name} {\n${body}}\n\n`;
        return name;
    }

    objectStruct(name: string, schema: JsonSchema, doc: string): string {
        const struct = unique(this.types, name);
        const required = new Set(Array.isArray(schema.required) ? (schema.required as string[]) : []);
        const fields = new Set<string>();
        const body = Object.entries((schema.properties as Record<string, JsonSchema> | undefined) ?? {})
            .map(([key, property]) => {
                const kind = this.typeOf(struct, key, property);
                const optional = !required.has(key);
                // Optional wraps once more even when nullable: `Some(None)` sends null, `None` sends nothing.
                return field(key, unique(fields, fieldIdent(key)), optional ? `Option<${kind}>` : kind, optional);
            })
            .join("");
        this.items += `/// ${doc}\n#[derive(Clone, Debug, PartialEq, Serialize)]\npub struct ${struct} {\n${body}}\n\n`;
        return struct;
    }

    typeOf(owner: string, key: string, schema: unknown): string {
        if (typeof schema !== "object" || schema === null) return VALUE;
        const node = schema as JsonSchema;
        const union = node.anyOf ?? node.oneOf;
        if (Array.isArray(union)) {
            const rest = union.filter(variant => (variant as JsonSchema | null)?.type !== "null");
            return rest.length === 1 && rest.length < union.length
                ? `Option<${this.typeOf(owner, key, rest[0])}>`
                : VALUE;
        }
        const types = [node.type].flat().filter((name): name is string => typeof name === "string");
        const bare = types.filter(name => name !== "null");
        const [only] = bare;
        if (only === undefined || bare.length !== 1) return VALUE;
        const inner = SCALARS[only] ?? this.compoundType(owner, key, only, node);
        return types.length > bare.length ? `Option<${inner}>` : inner;
    }

    private compoundType(owner: string, key: string, type: string, node: JsonSchema): string {
        switch (type) {
            case "string":
                return Array.isArray(node.enum) ? this.stringEnum(owner, key, node.enum) : "String";
            case "array":
                return `Vec<${this.typeOf(owner, key, node.items)}>`;
            case "object":
                if (node.properties)
                    return this.objectStruct(`${owner}${pascal(key)}`, node, `\`${docText(key)}\` of \`${owner}\`.`);
                // A map with typed values (`z.record`); an open object stays a Value.
                return typeof node.additionalProperties === "object" && node.additionalProperties !== null
                    ? `::std::collections::HashMap<String, ${this.typeOf(owner, key, node.additionalProperties)}>`
                    : VALUE;
            default:
                return VALUE;
        }
    }

    stringEnum(owner: string, key: string, values: readonly unknown[]): string {
        if (!values.every((value): value is string => typeof value === "string")) return VALUE;
        const name = unique(this.types, `${owner}${pascal(key)}`);
        const variants = new Set<string>();
        const body = values
            .map(value => `    #[serde(rename = ${rustString(value)})]\n    ${unique(variants, pascal(value))},\n`)
            .join("");
        this.items += `/// \`${docText(key)}\` of \`${owner}\`.\n#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]\npub enum ${name} {\n${body}}\n\n`;
        return name;
    }

    finish(): string {
        const client = [this.mutations && "Mutation", this.queries && "Query"].filter(Boolean);
        const serde = this.rows.size > 0 ? "{Deserialize, Serialize}" : this.items ? "Serialize" : "";
        const uses = `${client.length > 0 ? `use chardb_client::${client.length > 1 ? `{${client.join(", ")}}` : client[0]};\n` : ""}${serde ? `use serde::${serde};\n` : ""}`;
        return `${RUST_HEADER}\n${uses}${uses ? "\n" : ""}${this.items}${this.queries}${this.mutations}`
            .trimEnd()
            .concat("\n");
    }
}

export function renderRustModule(handles: readonly ApiHandle[]): string {
    const generator = new Generator();
    for (const { name, ref, kind, argsSchema, row } of handles) {
        const args = generator.argsType(name, argsSchema);
        if (kind === "mutation") generator.handle("Mutation", name, ref, args, VALUE);
        else generator.handle("Query", name, ref, args, row ? generator.rowType(row) : VALUE);
    }
    return generator.finish();
}
