/** Render the typed `@chardb/core` handle module for an app's handles. */

import type { Column } from "drizzle-orm";
import { type ApiHandle, type ApiRow, type JsonSchema, pascal, unique, words } from "./api-handles.ts";

export const TS_HEADER = "// Typed CharDB handles generated by `chardb generate`. Do not edit.\n";
const HANDLE = `const handle = (kind: string, ref: string): unknown =>
    Object.defineProperties(
        function chardbHandle(): never {
            throw new Error(\`CharDB \${kind} \${ref} cannot execute here; pass it to a CharDB client\`);
        },
        { __chardbKind: { value: kind }, __chardbRef: { value: ref } }
    );
`;
const MAX_WIDTH = 120;
const RAW = "RawJson";
const RESERVED = new Set(
    "arguments await break case catch class const continue debugger default delete do else enum eval export extends false finally for function if implements import in instanceof interface let new null package private protected public return static super switch this throw true try typeof var void while with yield".split(
        " "
    )
);
const IDENT = /^[\p{ID_Start}$_][\p{ID_Continue}$]*$/u;
/** TypeScript type per Drizzle `dataType` once the driver has mapped the SQLite value to JSON. */
const COLUMN_TYPES: Readonly<Record<string, string>> = { string: "string", number: "number", boolean: "boolean" };
const SCALARS: Readonly<Record<string, string>> = {
    string: "string",
    integer: "number",
    number: "number",
    boolean: "boolean",
};

const propertyKey = (key: string): string => (IDENT.test(key) ? key : JSON.stringify(key));
/** An export name: the app's key when it is an identifier, otherwise its words joined in camel case. */
function exportName(name: string): string {
    if (IDENT.test(name) && !RESERVED.has(name)) return name;
    const camel = words(name)
        .map((word, index) => (index === 0 ? word : word.replace(/^./u, first => first.toUpperCase())))
        .join("");
    if (camel === "") return "unnamed";
    return `${/^\p{N}/u.test(camel) ? "_" : ""}${camel}${RESERVED.has(camel) ? "_" : ""}`;
}
/** Text placed in a doc comment: it must not close the comment or break the line. */
const docText = (text: string): string => text.replaceAll(/[\p{Cc}\p{Cs}]/gu, "").replaceAll("*/", "*\\/");

class Generator {
    items = "";
    handles = "";
    private readonly types = new Set<string>();
    private readonly consts = new Set(["handle", "MutationHandle", "QueryHandle", RAW]);
    private readonly rows = new Map<string, string>();
    private readonly kinds = new Set<string>();
    private raw = false;

    /** Export identifiers: names that already are identifiers keep them; the rest are derived, then made unique. */
    identifiers(handles: readonly ApiHandle[]): Map<ApiHandle, string> {
        const idents = new Map<ApiHandle, string>();
        for (const handle of handles) {
            if (exportName(handle.name) === handle.name) idents.set(handle, unique(this.consts, handle.name));
        }
        for (const handle of handles) {
            if (!idents.has(handle)) idents.set(handle, unique(this.consts, exportName(handle.name)));
        }
        return idents;
    }

    handle({ ref, kind }: ApiHandle, ident: string, args: string, result: string): void {
        const alias = `${kind === "query" ? "Query" : "Mutation"}Handle`;
        this.kinds.add(alias);
        const head = `export const ${ident} = handle(${JSON.stringify(kind)}, ${JSON.stringify(ref)})`;
        const line = `${head} as ${alias}<${args}, ${result}>;`;
        // The two break shapes biome chooses once the line overflows: type arguments first, then call arguments.
        const body =
            line.length <= MAX_WIDTH
                ? line
                : `${head} as ${alias}<`.length <= MAX_WIDTH
                  ? `${head} as ${alias}<\n    ${args},\n    ${result}\n>;`
                  : `export const ${ident} = handle(\n    ${JSON.stringify(kind)},\n    ${JSON.stringify(ref)}\n) as ${alias}<${args}, ${result}>;`;
        this.handles += `/** \`${docText(ref)}\` */\n${body}\n`;
    }

    rawJson(): string {
        this.raw = true;
        return RAW;
    }

    argsType(owner: string, schema: JsonSchema | null): string {
        if (!schema) return `{ [key: string]: ${this.rawJson()} }`;
        if (schema.type !== "object" || !schema.properties) return this.typeOf(schema, "");
        const name = unique(this.types, `${pascal(owner)}Args`);
        this.items += `/** Arguments for \`${docText(owner)}\`. */\nexport type ${name} = ${this.objectType(schema, "")};\n\n`;
        return name;
    }

    rowType(row: ApiRow): string {
        const known = this.rows.get(row.table);
        if (known) return known;
        const name = unique(this.types, `${pascal(row.table)}Row`);
        this.rows.set(row.table, name);
        const body = row.columns.map(({ key, column }) => `    ${propertyKey(key)}: ${this.columnType(column)};\n`);
        this.items += `/** One \`${docText(row.table)}\` row. */\nexport type ${name} = {\n${body.join("")}};\n\n`;
        return name;
    }

    private columnType(column: Column): string {
        const base =
            column.columnType === "SQLiteInteger" ? "number" : (COLUMN_TYPES[column.dataType] ?? this.rawJson());
        return column.notNull ? base : `${base} | null`;
    }

    private objectType(schema: JsonSchema, indent: string): string {
        const properties = Object.entries((schema.properties as Record<string, unknown> | undefined) ?? {});
        if (properties.length === 0) return "Record<string, never>";
        const required = new Set(Array.isArray(schema.required) ? (schema.required as string[]) : []);
        const inner = `${indent}    `;
        // Validators accept an explicit undefined for an optional key, so under exactOptionalPropertyTypes the type must too.
        const body = properties.map(([key, property]) =>
            required.has(key)
                ? `${inner}${propertyKey(key)}: ${this.typeOf(property, inner)};\n`
                : `${inner}${propertyKey(key)}?: ${this.typeOf(property, inner)} | undefined;\n`
        );
        return `{\n${body.join("")}${indent}}`;
    }

    private typeOf(schema: unknown, indent: string): string {
        if (typeof schema !== "object" || schema === null) return this.rawJson();
        const node = schema as JsonSchema;
        if (Array.isArray(node.enum) && node.enum.every(value => typeof value === "string")) {
            return node.enum.map(value => JSON.stringify(value)).join(" | ");
        }
        if ("const" in node && (typeof node.const !== "object" || node.const === null))
            return JSON.stringify(node.const);
        const union = node.anyOf ?? node.oneOf;
        if (Array.isArray(union)) {
            return union.length > 0 ? union.map(variant => this.typeOf(variant, indent)).join(" | ") : this.rawJson();
        }
        const types = [node.type].flat().filter((name): name is string => typeof name === "string");
        const bare = types.filter(name => name !== "null");
        const [only] = bare;
        if (only === undefined) return types.length === 1 ? "null" : this.rawJson();
        if (bare.length !== 1) return this.rawJson();
        const inner = SCALARS[only] ?? this.compoundType(only, node, indent);
        return types.length > bare.length ? `${inner} | null` : inner;
    }

    private compoundType(type: string, node: JsonSchema, indent: string): string {
        switch (type) {
            case "array": {
                const item = this.typeOf(node.items, indent);
                return item.includes(" | ") ? `(${item})[]` : `${item}[]`;
            }
            case "object":
                if (node.properties) return this.objectType(node, indent);
                // A map with typed values (`z.record`); an open object stays untyped JSON.
                return typeof node.additionalProperties === "object" && node.additionalProperties !== null
                    ? `{ [key: string]: ${this.typeOf(node.additionalProperties, indent)} }`
                    : this.rawJson();
            default:
                return this.rawJson();
        }
    }

    finish(): string {
        if (this.handles === "") return `${TS_HEADER}export {};\n`;
        const names = [...this.kinds, ...(this.raw ? [RAW] : [])].sort();
        const imports = `import type { ${names.join(", ")} } from "@chardb/core";\n`;
        return `${TS_HEADER}${imports}\n${this.items}${HANDLE}\n${this.handles}`;
    }
}

export function renderTsModule(handles: readonly ApiHandle[]): string {
    const generator = new Generator();
    const idents = generator.identifiers(handles);
    for (const handle of handles) {
        const args = generator.argsType(handle.name, handle.argsSchema);
        const result =
            handle.kind === "mutation"
                ? generator.rawJson()
                : handle.row
                  ? `${generator.rowType(handle.row)}[]`
                  : generator.rawJson();
        generator.handle(handle, idents.get(handle) ?? exportName(handle.name), args, result);
    }
    return generator.finish();
}
