// Typed CharDB handles generated by `chardb generate`. Do not edit.
import type { MutationHandle, QueryHandle, RawJson } from "@chardb/core";

/** One `messages` row. */
export type MessagesRow = {
    id: string;
    organizationId: string;
    body: string;
    createdAt: number;
    pinned: boolean;
    score: number | null;
    meta: RawJson | null;
};

/** Arguments for `listMessages`. */
export type ListMessagesArgs = {
    organizationId: string;
    limit?: number | undefined;
    kind?: "all" | "pinned" | undefined;
    scope?: "self" | "team" | undefined;
    filters?: { [key: string]: string } | undefined;
};

/** Arguments for `postMessage`. */
export type PostMessageArgs = {
    id: string;
    organizationId: string;
    body: string;
    type: string | null;
    tags?: string[] | undefined;
    dueAt?: string | null | undefined;
};

/** Arguments for `taggedMessages`. */
export type TaggedMessagesArgs = {
    organizationId?: string | undefined;
    ids?: string[] | undefined;
};

const handle = (kind: string, ref: string): unknown =>
    Object.defineProperties(
        function chardbHandle(): never {
            throw new Error(`CharDB ${kind} ${ref} cannot execute here; pass it to a CharDB client`);
        },
        { __chardbKind: { value: kind }, __chardbRef: { value: ref } }
    );

/** `src/queries.ts#allMessages` */
export const allMessages = handle("query", "src/queries.ts#allMessages") as QueryHandle<
    { [key: string]: RawJson },
    MessagesRow[]
>;
/** `src/api.ts#clearMessages` */
export const clearMessages = handle("mutation", "src/api.ts#clearMessages") as MutationHandle<
    { [key: string]: RawJson },
    RawJson
>;
/** `src/queries.ts#listMessages` */
export const listMessages = handle("query", "src/queries.ts#listMessages") as QueryHandle<
    ListMessagesArgs,
    MessagesRow[]
>;
/** `src/api.ts#postMessage` */
export const postMessage = handle("mutation", "src/api.ts#postMessage") as MutationHandle<PostMessageArgs, RawJson>;
/** `src/queries.ts#taggedMessages` */
export const taggedMessages = handle("query", "src/queries.ts#taggedMessages") as QueryHandle<
    TaggedMessagesArgs,
    MessagesRow[]
>;
