//! Typed CharDB handles generated by `chardb generate`. Do not edit.
#![allow(dead_code, nonstandard_style, clippy::all, clippy::pedantic)]

use chardb_client::{Mutation, Query};
use serde::{Deserialize, Serialize};

/// One `messages` row.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagesRow {
    pub id: String,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    pub body: String,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    pub pinned: bool,
    pub score: Option<f64>,
    pub meta: Option<::serde_json::Value>,
}

/// `kind` of `ListMessagesArgs`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
pub enum ListMessagesArgsKind {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "pinned")]
    Pinned,
}

/// `scope` of `ListMessagesArgs`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
pub enum ListMessagesArgsScope {
    #[serde(rename = "self")]
    Self_,
    #[serde(rename = "team")]
    Team,
}

/// Arguments for `listMessages`.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct ListMessagesArgs {
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<ListMessagesArgsKind>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<ListMessagesArgsScope>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filters: Option<::std::collections::HashMap<String, String>>,
}

/// Arguments for `postMessage`.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct PostMessageArgs {
    pub id: String,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    pub body: String,
    pub r#type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "dueAt")]
    pub due_at: Option<Option<String>>,
}

/// Arguments for `taggedMessages`.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct TaggedMessagesArgs {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "organizationId")]
    pub organization_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<String>>,
}

/// `src/queries.ts#allMessages`
pub const ALL_MESSAGES: Query<::serde_json::Value, MessagesRow> =
    Query::new("src/queries.ts#allMessages");

/// `src/queries.ts#listMessages`
pub const LIST_MESSAGES: Query<ListMessagesArgs, MessagesRow> =
    Query::new("src/queries.ts#listMessages");

/// `src/queries.ts#taggedMessages`
pub const TAGGED_MESSAGES: Query<TaggedMessagesArgs, MessagesRow> =
    Query::new("src/queries.ts#taggedMessages");

/// `src/api.ts#clearMessages`
pub const CLEAR_MESSAGES: Mutation<::serde_json::Value, ::serde_json::Value> =
    Mutation::new("src/api.ts#clearMessages");

/// `src/api.ts#postMessage`
pub const POST_MESSAGE: Mutation<PostMessageArgs, ::serde_json::Value> =
    Mutation::new("src/api.ts#postMessage");
