//! Typed CharDB handles generated by `chardb api rust`. Do not edit.
#![allow(dead_code, clippy::all, clippy::pedantic)]

use chardb_client::{Mutation, Query};
use serde::{Deserialize, Serialize};

/// `kind` of [`ListMessagesArgs`].
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
pub enum ListMessagesArgsKind {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "pinned")]
    Pinned,
}

/// Arguments for `listMessages`.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct ListMessagesArgs {
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<ListMessagesArgsKind>,
}

/// One `messages` row.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagesRow {
    pub id: String,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    pub body: String,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    pub pinned: bool,
    pub score: Option<f64>,
    pub meta: Option<::serde_json::Value>,
}

/// Arguments for `postMessage`.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct PostMessageArgs {
    pub id: String,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    pub body: String,
    pub r#type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

/// `src/queries.ts#listMessages`
pub const LIST_MESSAGES: Query<ListMessagesArgs, MessagesRow> =
    Query::new("src/queries.ts#listMessages");

/// `src/api.ts#clearMessages`
pub const CLEAR_MESSAGES: Mutation<::serde_json::Value, ::serde_json::Value> =
    Mutation::new("src/api.ts#clearMessages");

/// `src/api.ts#postMessage`
pub const POST_MESSAGE: Mutation<PostMessageArgs, ::serde_json::Value> =
    Mutation::new("src/api.ts#postMessage");
