import { fileURLToPath, pathToFileURL } from "node:url";
import type { StandardJSONSchemaV1, StandardSchemaV1 } from "@standard-schema/spec";
import { type Column, getTableColumns, getTableName, is } from "drizzle-orm";
import { SQLiteTable } from "drizzle-orm/sqlite-core";
import type { RegisteredQueryPlan } from "../../server/registered-query-plan.ts";
import type { CliContext } from "../context.ts";

const WORKER_ENTRY = "src/worker.ts";
const INSPECTION_TIMEOUT_MS = 15_000;
const INSPECTION_OUTPUT_BYTES = 16 * 1_024 * 1_024 + 1_024;
const HEADER = `//! Typed CharDB handles generated by \`chardb api rust\`. Do not edit.
#![allow(dead_code, clippy::all, clippy::pedantic)]
`;
const MAX_WIDTH = 100;
const VALUE = "::serde_json::Value";
const KEYWORDS = new Set(
    "abstract as async await become box break const continue do dyn else enum extern false final fn for gen if impl in let loop macro match mod move mut override priv pub ref return static struct trait true try type typeof unsafe unsized use virtual where while yield".split(
        " "
    )
);
const UNRAWABLE = new Set(["self", "Self", "super", "crate"]);
/** Rust type per Drizzle `dataType` once the driver has mapped the SQLite value to JSON. */
const COLUMN_TYPES: Readonly<Record<string, string>> = {
    string: "String",
    date: "String",
    number: "f64",
    bigint: "i64",
    boolean: "bool",
};
const WORD = /\p{Lu}+(?=\p{Lu}\p{Ll})|\p{Lu}?[\p{Ll}\p{N}]+|\p{Lu}+/gu;

export interface ApiRustOptions {
    readonly out: string;
    readonly check?: boolean;
}

interface MarkedHandle {
    readonly __chardbKind: "query" | "mutation";
    readonly __chardbRef: string;
    readonly __chardbArgs?: StandardSchemaV1;
    readonly __chardbCompilePlan?: (args: unknown) => RegisteredQueryPlan;
}

type Schema = Record<string, unknown>;

function isMarked(value: unknown): value is MarkedHandle {
    if (typeof value !== "function" && (typeof value !== "object" || value === null)) return false;
    const marker = value as Partial<MarkedHandle>;
    return typeof marker.__chardbRef === "string" && typeof marker.__chardbKind === "string";
}

function jsonSchemaOf(ref: string, validator: StandardSchemaV1 | undefined): Schema | null {
    if (!validator) return null;
    const props = validator["~standard"] as StandardSchemaV1.Props & Partial<StandardJSONSchemaV1.Props>;
    if (!props.jsonSchema) {
        throw new Error(`${ref}: ${props.vendor} args validator does not implement Standard JSON Schema`);
    }
    return props.jsonSchema.input({ target: "draft-2020-12" });
}

/** Smallest value the schema admits, used only to compile the planned select. */
function sampleOf(schema: unknown): unknown {
    if (typeof schema !== "object" || schema === null) return null;
    const node = schema as Schema;
    if ("const" in node) return node.const;
    if (Array.isArray(node.enum) && node.enum.length > 0) return node.enum[0];
    const union = node.anyOf ?? node.oneOf;
    if (Array.isArray(union) && union.length > 0) return sampleOf(union[0]);
    switch (Array.isArray(node.type) ? node.type[0] : node.type) {
        case "string":
            return "x";
        case "integer":
        case "number":
            return typeof node.minimum === "number" ? node.minimum : 1;
        case "boolean":
            return true;
        case "array":
            return [sampleOf(node.items)];
        case "object":
            return Object.fromEntries(
                Object.entries((node.properties as Schema | undefined) ?? {}).map(([key, value]) => [
                    key,
                    sampleOf(value),
                ])
            );
        default:
            return null;
    }
}

function columnType(column: Column): string {
    const base = column.columnType === "SQLiteInteger" ? "i64" : (COLUMN_TYPES[column.dataType] ?? VALUE);
    return column.notNull || column.primary ? base : `Option<${base}>`;
}

/** Lowercase words split on separators and camel-case boundaries. */
function words(text: string): string[] {
    return (text.match(WORD) ?? []).map(word => word.toLowerCase());
}

function pascal(text: string): string {
    const name = words(text)
        .map(word => word.replace(/^./u, first => first.toUpperCase()))
        .join("");
    return /^\p{N}/u.test(name) ? `N${name}` : name || "Unnamed";
}

function snake(text: string): string {
    const name = words(text).join("_");
    return /^\p{N}/u.test(name) ? `_${name}` : name || "unnamed";
}

function fieldIdent(key: string): string {
    const name = snake(key);
    return KEYWORDS.has(name) ? `r#${name}` : UNRAWABLE.has(name) ? `${name}_` : name;
}

function field(key: string, kind: string, optional: boolean): string {
    const ident = fieldIdent(key);
    return `${optional ? '    #[serde(skip_serializing_if = "Option::is_none")]\n' : ""}${
        ident.replace(/^r#/, "") === key ? "" : `    #[serde(rename = ${JSON.stringify(key)})]\n`
    }    pub ${ident}: ${kind},\n`;
}

class Generator {
    items = "";
    readonly rows = new Set<string>();

    handle(kind: "Query" | "Mutation", name: string, reference: string, args: string, output: string): string {
        const head = `pub const ${snake(name).toUpperCase()}: ${kind}<${args}, ${output}> =`;
        const tail = `${kind}::new(${JSON.stringify(reference)});`;
        return `/// \`${reference}\`\n${head}${head.length + tail.length < MAX_WIDTH ? " " : "\n    "}${tail}\n\n`;
    }

    argsType(owner: string, schema: Schema | null): string {
        if (schema?.type !== "object") return VALUE;
        const name = `${pascal(owner)}Args`;
        this.objectStruct(name, schema, `Arguments for \`${owner}\`.`);
        return name;
    }

    rowType(ref: string, plan: RegisteredQueryPlan, schema: Schema): string {
        if (plan.kind !== "select") return VALUE;
        const table = Object.values(schema).find(
            (value): value is SQLiteTable => is(value, SQLiteTable) && getTableName(value) === plan.plan.table
        );
        if (!table) throw new Error(`${ref}: table ${plan.plan.table} is not part of the worker schema`);
        const name = `${pascal(plan.plan.table)}Row`;
        if (this.rows.has(plan.plan.table)) return name;
        this.rows.add(plan.plan.table);
        const columns = getTableColumns(table) as Record<string, Column>;
        const body = plan.projection
            .map(({ key }) => {
                const column = columns[key];
                if (!column) throw new Error(`${ref}: column ${key} is not part of ${plan.plan.table}`);
                return field(key, columnType(column), false);
            })
            .join("");
        this.items += `/// One \`${plan.plan.table}\` row.\n#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\npub struct ${name} {\n${body}}\n\n`;
        return name;
    }

    objectStruct(name: string, schema: Schema, doc: string): void {
        const required = new Set(Array.isArray(schema.required) ? (schema.required as string[]) : []);
        const body = Object.entries((schema.properties as Record<string, Schema> | undefined) ?? {})
            .map(([key, property]) => {
                const kind = this.typeOf(name, key, property);
                const optional = !required.has(key);
                return field(key, optional && !kind.startsWith("Option<") ? `Option<${kind}>` : kind, optional);
            })
            .join("");
        this.items += `/// ${doc}\n#[derive(Clone, Debug, PartialEq, Serialize)]\npub struct ${name} {\n${body}}\n\n`;
    }

    typeOf(owner: string, key: string, schema: unknown): string {
        if (typeof schema !== "object" || schema === null) return VALUE;
        const node = schema as Schema;
        const union = node.anyOf ?? node.oneOf;
        if (Array.isArray(union)) {
            const rest = union.filter(variant => (variant as Schema | null)?.type !== "null");
            return rest.length === 1 && rest.length < union.length
                ? `Option<${this.typeOf(owner, key, rest[0])}>`
                : VALUE;
        }
        const types = [node.type].flat().filter((name): name is string => typeof name === "string");
        const bare = types.filter(name => name !== "null");
        if (bare.length !== 1) return VALUE;
        let inner: string;
        switch (bare[0]) {
            case "string":
                inner = Array.isArray(node.enum) ? this.stringEnum(owner, key, node.enum) : "String";
                break;
            case "integer":
                inner = "i64";
                break;
            case "number":
                inner = "f64";
                break;
            case "boolean":
                inner = "bool";
                break;
            case "array":
                inner = `Vec<${this.typeOf(owner, key, node.items)}>`;
                break;
            case "object": {
                inner = `${owner}${pascal(key)}`;
                this.objectStruct(inner, node, `\`${key}\` of [\`${owner}\`].`);
                break;
            }
            default:
                return VALUE;
        }
        return types.length > bare.length ? `Option<${inner}>` : inner;
    }

    stringEnum(owner: string, key: string, values: readonly unknown[]): string {
        if (!values.every((value): value is string => typeof value === "string")) return VALUE;
        const name = `${owner}${pascal(key)}`;
        const body = values
            .map(value => `    #[serde(rename = ${JSON.stringify(value)})]\n    ${pascal(value)},\n`)
            .join("");
        this.items += `/// \`${key}\` of [\`${owner}\`].\n#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]\npub enum ${name} {\n${body}}\n\n`;
        return name;
    }

    finish(queries: string, mutations: string): string {
        const client = [mutations && "Mutation", queries && "Query"].filter(Boolean);
        const serde = this.rows.size > 0 ? "{Deserialize, Serialize}" : this.items ? "Serialize" : "";
        const uses = `${client.length > 0 ? `use chardb_client::${client.length > 1 ? `{${client.join(", ")}}` : client[0]};\n` : ""}${serde ? `use serde::${serde};\n` : ""}`;
        return `${HEADER}\n${uses}${uses ? "\n" : ""}${this.items}${queries}${mutations}`.trimEnd().concat("\n");
    }
}

/** Render one Rust module for the handles an app registered through `chardb({ api })`. */
export function renderRustModule(refs: Readonly<Record<string, unknown>>, schema: Schema): string {
    const generator = new Generator();
    const handles = Object.entries(refs)
        .filter((entry): entry is [string, MarkedHandle] => isMarked(entry[1]))
        .sort(([left], [right]) => (left < right ? -1 : 1));
    const seen = new Set<string>();
    let queries = "";
    let mutations = "";
    for (const [name, handle] of handles) {
        const ref = handle.__chardbRef;
        if (seen.has(ref)) continue;
        seen.add(ref);
        const argsSchema = jsonSchemaOf(ref, handle.__chardbArgs);
        const args = generator.argsType(name, argsSchema);
        if (handle.__chardbKind === "mutation") {
            mutations += generator.handle("Mutation", name, ref, args, VALUE);
            continue;
        }
        const plan =
            argsSchema && handle.__chardbCompilePlan ? handle.__chardbCompilePlan(sampleOf(argsSchema)) : undefined;
        queries += generator.handle("Query", name, ref, args, plan ? generator.rowType(ref, plan, schema) : VALUE);
    }
    return generator.finish(queries, mutations);
}

interface WorkerApp {
    readonly api: Readonly<Record<string, unknown>>;
    readonly schema: Schema;
}

function isWorkerApp(value: unknown): value is WorkerApp {
    if ((typeof value !== "object" && typeof value !== "function") || value === null) return false;
    const app = value as { readonly api?: unknown; readonly DB?: unknown };
    return typeof app.api === "object" && app.api !== null && typeof app.DB === "function";
}

/** Hidden fresh-process boundary used only by `api rust`. */
export async function runApiInspect(ctx: CliContext): Promise<void> {
    const worker = (await import(pathToFileURL(`${ctx.cwd}/${WORKER_ENTRY}`).href)) as Record<string, unknown>;
    const app = [worker.default, ...Object.values(worker)].find(isWorkerApp);
    if (!app) throw new Error(`${WORKER_ENTRY} must export the app returned by chardb()`);
    ctx.stdout(renderRustModule(app.api, app.schema));
}

function inspectorSelfArgs(executable: string, args: readonly string[]): readonly string[] {
    if (executable !== process.execPath) return args;
    const source = import.meta.url.endsWith(".ts");
    const preloadPath = fileURLToPath(
        new URL(source ? "../schema-inspector-preload.ts" : "../cli/schema-inspector-preload.mjs", import.meta.url)
    );
    return ["--preload", preloadPath, ...args];
}

/** Write the Rust module for `src/worker.ts`, or with `check` fail when the existing file is stale. */
export async function runApiRust(ctx: CliContext, options: ApiRustOptions): Promise<void> {
    if (!ctx.runCommand || !ctx.selfCommand) throw new Error("fresh Bun api inspection is unavailable");
    if (!(await ctx.exists(`${ctx.cwd}/${WORKER_ENTRY}`))) throw new Error(`${WORKER_ENTRY} is missing`);
    const result = await ctx.runCommand({
        executable: ctx.selfCommand.executable,
        args: [...inspectorSelfArgs(ctx.selfCommand.executable, ctx.selfCommand.args), "__api-inspect"],
        cwd: ctx.cwd,
        timeoutMs: INSPECTION_TIMEOUT_MS,
        maxOutputBytes: INSPECTION_OUTPUT_BYTES,
    });
    if (result.exitCode !== 0) {
        const detail = result.stderr.trim().replaceAll(/\s+/g, " ").slice(0, 2_048);
        throw new Error(detail.length > 0 ? detail : "api inspection failed in a fresh Bun process");
    }
    if (result.stderr.length > 0 || !result.stdout.startsWith(HEADER)) {
        throw new Error("api inspector returned malformed output");
    }
    const path = options.out.startsWith("/") ? options.out : `${ctx.cwd}/${options.out}`;
    if ((await ctx.exists(path)) && (await ctx.read(path)) === result.stdout) return;
    if (options.check) throw new Error(`${options.out} is stale; run chardb api rust --out ${options.out}`);
    await ctx.write(path, result.stdout);
}
