import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { StandardJSONSchemaV1, StandardSchemaV1 } from "@standard-schema/spec";
import { type Column, getTableColumns, getTableName, is } from "drizzle-orm";
import { SQLiteTable } from "drizzle-orm/sqlite-core";
import { type ChardbRefMarker, isRefMarked } from "../../server/refs.ts";
import type { RegisteredQueryPlan } from "../../server/registered-query-plan.ts";
import type { CliContext } from "../context.ts";
import { runInspection } from "../inspector.ts";

const WORKER_ENTRY = "src/worker.ts";
const HEADER = `//! Typed CharDB handles generated by \`chardb api rust\`. Do not edit.
#![allow(dead_code, clippy::all, clippy::pedantic)]
`;
const MAX_WIDTH = 100;
const VALUE = "::serde_json::Value";
const KEYWORDS = new Set(
    "abstract as async await become box break const continue do dyn else enum extern false final fn for gen if impl in let loop macro match mod move mut override priv pub ref return static struct trait true try type typeof unsafe unsized use virtual where while yield".split(
        " "
    )
);
const UNRAWABLE = new Set(["self", "Self", "super", "crate"]);
/** Rust type per Drizzle `dataType` once the driver has mapped the SQLite value to JSON. */
const COLUMN_TYPES: Readonly<Record<string, string>> = {
    string: "String",
    date: "String",
    number: "f64",
    bigint: "i64",
    boolean: "bool",
};
/** JSON Schema scalars with one fixed Rust spelling. */
const SCALARS: Readonly<Record<string, string>> = { integer: "i64", number: "f64", boolean: "bool" };
const WORD = /\p{Lu}+(?=\p{Lu}\p{Ll})|\p{Lu}?[\p{Ll}\p{N}]+|\p{Lu}+/gu;

export interface ApiRustOptions {
    readonly out: string;
    readonly check?: boolean;
}

interface MarkedHandle extends ChardbRefMarker {
    readonly __chardbArgs?: StandardSchemaV1;
    readonly __chardbCompilePlan?: (args: unknown) => RegisteredQueryPlan;
}

type Schema = Record<string, unknown>;

function withRef<T>(ref: string, run: () => T): T {
    try {
        return run();
    } catch (error) {
        throw new Error(`${ref}: ${error instanceof Error ? error.message : String(error)}`);
    }
}

function jsonSchemaOf(ref: string, validator: StandardSchemaV1 | undefined): Schema | null {
    if (!validator) return null;
    const props = validator["~standard"] as StandardSchemaV1.Props & Partial<StandardJSONSchemaV1.Props>;
    if (!props.jsonSchema) {
        throw new Error(`${ref}: ${props.vendor} args validator does not implement Standard JSON Schema`);
    }
    // zod describes what it cannot represent as `{}`, which becomes a Value below instead of aborting the run.
    const options = { target: "draft-2020-12", libraryOptions: { unrepresentable: "any" } } as const;
    return withRef(ref, () => props.jsonSchema?.input(options) ?? null);
}

/** One value per schema node, enough to compile the planned select; it need not satisfy every constraint. */
function sampleOf(schema: unknown): unknown {
    if (typeof schema !== "object" || schema === null) return null;
    const node = schema as Schema;
    if ("default" in node) return node.default;
    if ("const" in node) return node.const;
    if (Array.isArray(node.enum) && node.enum.length > 0) return node.enum[0];
    const union = node.anyOf ?? node.oneOf;
    if (Array.isArray(union) && union.length > 0) return sampleOf(union[0]);
    switch (Array.isArray(node.type) ? node.type[0] : node.type) {
        case "string":
            return "x";
        case "integer":
        case "number":
            // Planned selects reject limit(0), so the sample never drops below one.
            return typeof node.minimum === "number" ? Math.max(node.minimum, 1) : 1;
        case "boolean":
            return true;
        case "array":
            return [sampleOf(node.items)];
        case "object":
            return Object.fromEntries(
                Object.entries((node.properties as Schema | undefined) ?? {}).map(([key, value]) => [
                    key,
                    sampleOf(value),
                ])
            );
        default:
            return null;
    }
}

function columnType(column: Column): string {
    const base = column.columnType === "SQLiteInteger" ? "i64" : (COLUMN_TYPES[column.dataType] ?? VALUE);
    return column.notNull || column.primary ? base : `Option<${base}>`;
}

/** Lowercase words split on separators and camel-case boundaries. */
function words(text: string): string[] {
    return (text.match(WORD) ?? []).map(word => word.toLowerCase());
}

function pascal(text: string): string {
    const joined = words(text)
        .map(word => word.replace(/^./u, first => first.toUpperCase()))
        .join("");
    const name = /^\p{N}/u.test(joined) ? `N${joined}` : joined || "Unnamed";
    return UNRAWABLE.has(name) ? `${name}_` : name;
}

function snake(text: string): string {
    const name = words(text).join("_");
    return /^\p{N}/u.test(name) ? `_${name}` : name || "unnamed";
}

function fieldIdent(key: string): string {
    const name = snake(key);
    return KEYWORDS.has(name) ? `r#${name}` : UNRAWABLE.has(name) ? `${name}_` : name;
}

/** Distinct wire names stay distinct in Rust: a repeat gets a counter while the serde rename keeps the wire key. */
function unique(taken: Set<string>, ident: string): string {
    let name = ident;
    for (let n = 2; taken.has(name); n++) name = `${ident}_${n}`;
    taken.add(name);
    return name;
}

function field(key: string, ident: string, kind: string, optional: boolean): string {
    return `${optional ? '    #[serde(skip_serializing_if = "Option::is_none")]\n' : ""}${
        ident.replace(/^r#/, "") === key ? "" : `    #[serde(rename = ${JSON.stringify(key)})]\n`
    }    pub ${ident}: ${kind},\n`;
}

class Generator {
    items = "";
    queries = "";
    mutations = "";
    private readonly types = new Set<string>();
    private readonly consts = new Set<string>();
    private readonly rows = new Map<string, string>();

    handle(kind: "Query" | "Mutation", name: string, reference: string, args: string, output: string): void {
        const head = `pub const ${unique(this.consts, snake(name).toUpperCase())}: ${kind}<${args}, ${output}> =`;
        const tail = `${kind}::new(${JSON.stringify(reference)});`;
        const gap = head.length + tail.length < MAX_WIDTH ? " " : "\n    ";
        this[kind === "Query" ? "queries" : "mutations"] += `/// \`${reference}\`\n${head}${gap}${tail}\n\n`;
    }

    argsType(owner: string, schema: Schema | null): string {
        if (!schema) return VALUE;
        if (schema.type === "object" && schema.properties) {
            return this.objectStruct(`${pascal(owner)}Args`, schema, `Arguments for \`${owner}\`.`);
        }
        return this.typeOf(pascal(owner), "Args", schema);
    }

    rowType(ref: string, plan: RegisteredQueryPlan, schema: Schema): string {
        if (plan.kind !== "select") return VALUE;
        const known = this.rows.get(plan.plan.table);
        if (known) return known;
        const table = Object.values(schema).find(
            (value): value is SQLiteTable => is(value, SQLiteTable) && getTableName(value) === plan.plan.table
        );
        if (!table) throw new Error(`${ref}: table ${plan.plan.table} is not part of the worker schema`);
        const name = unique(this.types, `${pascal(plan.plan.table)}Row`);
        this.rows.set(plan.plan.table, name);
        const columns = getTableColumns(table) as Record<string, Column>;
        const fields = new Set<string>();
        const body = plan.projection
            .map(({ key }) => {
                const column = columns[key];
                if (!column) throw new Error(`${ref}: column ${key} is not part of ${plan.plan.table}`);
                return field(key, unique(fields, fieldIdent(key)), columnType(column), false);
            })
            .join("");
        this.items += `/// One \`${plan.plan.table}\` row.\n#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\npub struct ${name} {\n${body}}\n\n`;
        return name;
    }

    objectStruct(name: string, schema: Schema, doc: string): string {
        const struct = unique(this.types, name);
        const required = new Set(Array.isArray(schema.required) ? (schema.required as string[]) : []);
        const fields = new Set<string>();
        const body = Object.entries((schema.properties as Record<string, Schema> | undefined) ?? {})
            .map(([key, property]) => {
                const kind = this.typeOf(struct, key, property);
                const optional = !required.has(key);
                // Optional wraps once more even when nullable: `Some(None)` sends null, `None` sends nothing.
                return field(key, unique(fields, fieldIdent(key)), optional ? `Option<${kind}>` : kind, optional);
            })
            .join("");
        this.items += `/// ${doc}\n#[derive(Clone, Debug, PartialEq, Serialize)]\npub struct ${struct} {\n${body}}\n\n`;
        return struct;
    }

    typeOf(owner: string, key: string, schema: unknown): string {
        if (typeof schema !== "object" || schema === null) return VALUE;
        const node = schema as Schema;
        const union = node.anyOf ?? node.oneOf;
        if (Array.isArray(union)) {
            const rest = union.filter(variant => (variant as Schema | null)?.type !== "null");
            return rest.length === 1 && rest.length < union.length
                ? `Option<${this.typeOf(owner, key, rest[0])}>`
                : VALUE;
        }
        const types = [node.type].flat().filter((name): name is string => typeof name === "string");
        const bare = types.filter(name => name !== "null");
        const [only] = bare;
        if (only === undefined || bare.length !== 1) return VALUE;
        const inner = SCALARS[only] ?? this.compoundType(owner, key, only, node);
        return types.length > bare.length ? `Option<${inner}>` : inner;
    }

    private compoundType(owner: string, key: string, type: string, node: Schema): string {
        switch (type) {
            case "string":
                return Array.isArray(node.enum) ? this.stringEnum(owner, key, node.enum) : "String";
            case "array":
                return `Vec<${this.typeOf(owner, key, node.items)}>`;
            case "object":
                if (node.properties)
                    return this.objectStruct(`${owner}${pascal(key)}`, node, `\`${key}\` of [\`${owner}\`].`);
                // A map with typed values (`z.record`); an open object stays a Value.
                return typeof node.additionalProperties === "object" && node.additionalProperties !== null
                    ? `::std::collections::HashMap<String, ${this.typeOf(owner, key, node.additionalProperties)}>`
                    : VALUE;
            default:
                return VALUE;
        }
    }

    stringEnum(owner: string, key: string, values: readonly unknown[]): string {
        if (!values.every((value): value is string => typeof value === "string")) return VALUE;
        const name = unique(this.types, `${owner}${pascal(key)}`);
        const variants = new Set<string>();
        const body = values
            .map(value => `    #[serde(rename = ${JSON.stringify(value)})]\n    ${unique(variants, pascal(value))},\n`)
            .join("");
        this.items += `/// \`${key}\` of [\`${owner}\`].\n#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]\npub enum ${name} {\n${body}}\n\n`;
        return name;
    }

    finish(): string {
        const client = [this.mutations && "Mutation", this.queries && "Query"].filter(Boolean);
        const serde = this.rows.size > 0 ? "{Deserialize, Serialize}" : this.items ? "Serialize" : "";
        const uses = `${client.length > 0 ? `use chardb_client::${client.length > 1 ? `{${client.join(", ")}}` : client[0]};\n` : ""}${serde ? `use serde::${serde};\n` : ""}`;
        return `${HEADER}\n${uses}${uses ? "\n" : ""}${this.items}${this.queries}${this.mutations}`
            .trimEnd()
            .concat("\n");
    }
}

/** Render one Rust module for the handles an app registered through `chardb({ api })`. */
export function renderRustModule(refs: Readonly<Record<string, unknown>>, schema: Schema): string {
    const generator = new Generator();
    const handles = Object.entries(refs)
        .filter((entry): entry is [string, MarkedHandle] => isRefMarked(entry[1]))
        .sort(([left], [right]) => (left < right ? -1 : 1));
    const seen = new Map<string, MarkedHandle>();
    for (const [name, handle] of handles) {
        const ref = handle.__chardbRef;
        const previous = seen.get(ref);
        if (previous === handle) continue;
        if (previous) throw new Error(`${ref}: registered by two different handles`);
        seen.set(ref, handle);
        const argsSchema = jsonSchemaOf(ref, handle.__chardbArgs);
        const args = generator.argsType(name, argsSchema);
        if (handle.__chardbKind === "mutation") {
            generator.handle("Mutation", name, ref, args, VALUE);
            continue;
        }
        const plan = withRef(ref, () => handle.__chardbCompilePlan?.(argsSchema ? sampleOf(argsSchema) : undefined));
        generator.handle("Query", name, ref, args, plan ? generator.rowType(ref, plan, schema) : VALUE);
    }
    return generator.finish();
}

interface WorkerApp {
    readonly api: Readonly<Record<string, unknown>>;
    readonly schema: Schema;
}

function isWorkerApp(value: unknown): value is WorkerApp {
    if ((typeof value !== "object" && typeof value !== "function") || value === null) return false;
    const app = value as { readonly api?: unknown; readonly DB?: unknown };
    return typeof app.api === "object" && app.api !== null && typeof app.DB === "function";
}

/** Hidden fresh-process boundary used only by `api rust`. */
export async function runApiInspect(ctx: CliContext): Promise<void> {
    const worker = (await import(pathToFileURL(`${ctx.cwd}/${WORKER_ENTRY}`).href)) as Record<string, unknown>;
    const app = [worker.default, ...Object.values(worker)].find(isWorkerApp);
    if (!app) throw new Error(`${WORKER_ENTRY} must export the app returned by chardb()`);
    ctx.stdout(renderRustModule(app.api, app.schema));
}

/** Write the Rust module for `src/worker.ts`, or with `check` fail when the existing file is stale. */
export async function runApiRust(ctx: CliContext, options: ApiRustOptions): Promise<void> {
    if (!(await ctx.exists(`${ctx.cwd}/${WORKER_ENTRY}`))) throw new Error(`${WORKER_ENTRY} is missing`);
    const result = await runInspection(ctx, ["__api-inspect"]);
    // Warnings the app prints while loading are tolerated; they only surface when the module itself is missing.
    const detail = result.stderr.trim().replaceAll(/\s+/g, " ").slice(0, 2_048);
    if (result.exitCode !== 0) throw new Error(detail || "api inspection failed in a fresh Bun process");
    if (!result.stdout.startsWith(HEADER)) {
        throw new Error(`api inspector returned malformed output${detail ? `: ${detail}` : ""}`);
    }
    const path = resolve(ctx.cwd, options.out);
    if ((await ctx.exists(path)) && (await ctx.read(path)) === result.stdout) return;
    if (options.check) throw new Error(`${options.out} is stale; run chardb api rust --out ${options.out}`);
    await ctx.write(path, result.stdout);
}
